project_id = "diqdsmrlhldanxxrtozl"

[functions.send-email]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.get-vapid]
verify_jwt = false

[functions.notify-admins]
verify_jwt = true

[functions.notify-user]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.subscription-management]
verify_jwt = true

[functions.cleanup-old-offers]
verify_jwt = true

[functions.api-products]
verify_jwt = false

[functions.api-comparisons]
verify_jwt = false

[functions.api-docs]
verify_jwt = false

[functions.create-mp-checkout]
verify_jwt = true

[functions.mp-webhook]
verify_jwt = false
